routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('www.'.config('app.domain'))->group(function () {
    Route::get('{slug?}', function ($slug = null) {
        return redirect(config('app.url').($slug ?? ''), 301);
    })->where('slug', '(.*)');
});

// Authentication Routes
Route::get('entrar', 'Auth\LoginController@showLoginForm')->middleware('guest')->name('login');
Route::post('entrar', 'Auth\LoginController@login')->middleware('guest');
Route::post('sair', 'Auth\LoginController@logout')->name('logout');

// Grupos
Route::prefix('grupos/{grupo}')->name('grupo.')->group(__DIR__.'/group.php');

Route::domain(config('app.domain'))->group(function () {
    // Social Auth routes
    Route::namespace('Auth')->prefix('auth/{provider}')->name('social.')->group(function () {
        Route::get('/', 'LoginController@socialRedirect')->name('redirect');
        Route::get('callback', 'LoginController@socialCallback')->name('callback');

        // Social Link routes
        Route::get('link', 'SocialController@link')->name('link')->middleware('auth');
        Route::post('link', 'SocialController@linkConfirm')->name('linkConfirm')->middleware('auth');
        Route::delete('link', 'SocialController@unlink')->name('unlink')->middleware('auth');
    });

    // Password Reset Routes...
    Route::namespace('Auth')->prefix('password')->name('password.')->middleware('guest')->group(function () {
        Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('request');
        Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');
        Route::get('reset/{token}', 'ResetPasswordController@showResetForm')->name('reset');
        Route::post('reset', 'ResetPasswordController@reset');
    });

    Route::middleware('maintenance')->group(function () {
        Route::get('/', 'HomeController@index')->name('home');

        // Noticias
        Route::prefix('noticias')->name('noticias.')->group(function () {
            Route::get('/', 'NoticiasController@index')->name('index');
            Route::get('{noticia}', 'NoticiasController@show')->name('show');
        });

        // Pessoas
        Route::resource('pessoas', 'PessoasController', ['except' => ['index']]);
        Route::resource('pessoas.passos', 'PassosController', ['only' => ['store', 'destroy']]);
        Route::resource('pessoas.consentimentos', 'ConsentimentosController', ['only' => ['store', 'show', 'destroy']]);
        Route::prefix('pessoas')->name('pessoas.')->middleware('auth')->group(function () {
            Route::patch('{pessoa}/foto', 'PessoasController@updatePhoto')->name('updateFoto');
            Route::get('{pessoa}/enviar-link', 'PessoasController@sendPasswordResetLink')->name('sendResetLink');
            Route::post('{pessoa}/relacoes', 'RelacoesController@store')->name('relacoes.store');
            Route::delete('{pessoa}/relacoes/{pessoa2}', 'RelacoesController@destroy')->name('relacoes.destroy');

            Route::post('{pessoa}/permissoes', 'PermissionsController@addPermission')->name('permissions.add');
            Route::delete('{pessoa}/permissoes/{permission}', 'PermissionsController@removePermission')->name('permissions.remove');
            Route::post('{pessoa}/papeis', 'PermissionsController@addRole')->name('permissions.addRole');
            Route::delete('{pessoa}/papeis/{role}', 'PermissionsController@removeRole')->name('permissions.removeRole');
        });

        // Eu
        Route::middleware(['auth'])->prefix('eu')->name('me.')->group(function () {
            Route::get('/', 'EuController@conta')->name('account');
            Route::get('perfil', 'EuController@perfil')->name('profile');
            Route::get('edit', 'EuController@editPerfil')->name('editProfile');
            Route::get('grupos', 'EuController@grupos')->name('groups');
            Route::post('password', 'EuController@changePassword')->name('changePassword');
            Route::get('consentimento', 'ConsentimentosController@showRequest')->name('showConsentRequest');
            Route::post('consentimento', 'ConsentimentosController@storeRequest')->name('storeConsentRequest');
        });

        // Admin
        Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
            Route::get('/', 'AdminController@index')->name('dashboard')->middleware(['permission:ver pessoas|gerir pessoas|gerir grupos|gerir permissões|gerir notícias|gerir páginas|gerir opções|gerir eventos']);
            Route::get('pessoas', 'AdminController@pessoas')->name('people')->middleware(['permission:ver pessoas|gerir pessoas']);
            Route::resource('noticias', 'Admin\\NoticiasController', ['except' => ['show', 'store', 'update']])->middleware(['permission:gerir notícias']);
            Route::resource('paginas', 'Admin\\PaginasController', ['except' => ['show', 'store', 'update']])->middleware(['permission:gerir páginas']);
            Route::get('eventos', 'Admin\\EventosController@index')->name('eventos')->middleware(['permission:gerir eventos']);
            Route::get('permissoes', 'AdminController@permissoes')->name('permissoes')->middleware(['permission:gerir permissões']);

            Route::middleware(['permission:gerir grupos'])->prefix('grupos')->group(function () {
                Route::get('/', 'Admin\\GruposController@index')->name('groups');
                Route::post('/', 'Admin\\GruposController@store')->name('groups.store');
                Route::put('restore', 'Admin\\GruposController@restore')->name('groups.restore');
            });

            Route::middleware(['permission:gerir opções'])->group(function () {
                Route::get('extensoes', 'Admin\\AddonController@index')->name('extensoes');
                Route::post('extensoes/{key}', 'Admin\\AddonController@enable')->name('extensoes.enable');
                Route::delete('extensoes/{key}', 'Admin\\AddonController@disable')->name('extensoes.disable');

                Route::get('personalizar', 'Admin\\OpcoesController@personalizar')->name('personalizar');
                Route::post('personalizar', 'Admin\\OpcoesController@updatePersonalizar')->name('personalizar.update');

                Route::get('redirects', 'AdminController@redirects')->name('redirects');

                Route::get('definicoes', 'Admin\\OpcoesController@definicoes')->name('definicoes');
                Route::post('definicoes', 'Admin\\OpcoesController@updateDefinicoes')->name('definicoes.update');
            });

            Route::middleware(['permission:gerir domínios'])->get('dominios', 'AdminController@domains')->name('domains');
        });

        // 2FA
        Route::view('2fa-required', 'two-factor::notice')->name('2fa.notice');

        // Media
        Route::get('media/{uuid}', 'MediaController@show')->name('media');



        // Page catch all
        Route::get('{slug}', 'PaginasController@show')
            ->where('slug', '(.*)')->name('paginas.show');
    });
});

Route::domain('{grupo}.'.config('app.domain'))->group(function () {
    Route::get('{slug?}', function (Sautor\Core\Models\Grupo $grupo, $slug = null) {
        return redirect(config('app.url').route('grupo.index', $grupo, false).($slug ? '/'.$slug : ''));
    })->where('slug', '(.*)');
});

Route::domain('{grupo:dominio}')->where(['grupo' => '[a-z0-9.]+'])->name('grupo-dominio.')->middleware('maintenance')->group(function () {
    Route::get('noticias/{noticia}', 'GruposController@noticia')->where(['noticia' => '[0-9]+'])->name('noticia');

    require __DIR__.'/group.php';
});

resources/views/admin/customize.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header md:gap-3">
        <h1 class="admin-layout__header__title">
            Personalizar
        </h1>
    </header>

    <form method="POST" enctype="multipart/form-data">
    @csrf

        <section class="admin-settings__section">
            <header class="admin-settings__section__header">
                <h3 class="admin-settings__section__title">Identidade visual</h3>
            </header>
            <div class="admin-settings__section__content admin-settings__section__content--empty">
                <h6 class="font-headline mb-2 text-gray-600">Logótipo</h6>
                <div class="admin-settings__section__content admin-settings__section__body">

                    <div class="field">
                        <label class="label">
                            Logótipo
                            <span class="label__optional">(opcional)</span>
                        </label>
                        <div class="control">
                            <setting-file-picker name="site-logo" path="logos" accept="image/*" title="Escolher logótipo…" value="{{ Setting::get('site-logo') }}"></setting-file-picker>
                        </div>
                        <small class="field__help">
                            É recomendada uma imagem em formato PNG ou SVG, com fundo transparente.
                        </small>
                    </div>

                    <div class="field">
                        <label class="label">
                            Logótipo invertido
                            <span class="label__optional">(opcional)</span>
                        </label>
                        <div class="control">
                            <setting-file-picker name="site-logo-invert" path="logos" accept="image/*" title="Escolher logótipo invertido…" value="{{ Setting::get('site-logo-invert') }}" invert></setting-file-picker>
                        </div>
                        <small class="field__help">
                            É recomendada uma imagem em formato PNG ou SVG, com fundo transparente, para ser usada sobre fundos escuros ou da cor abaixo. Se não existir, será usado o logótipo principal.
                        </small>
                    </div>

                    <div class="field">
                        <label class="label">
                            Logomarca
                            <span class="label__optional">(opcional)</span>
                        </label>
                        <div class="control">
                            <setting-file-picker name="site-wordmark" path="logos" accept="image/*" title="Escolher logomarca…" value="{{ Setting::get('site-wordmark') }}" invert></setting-file-picker>
                        </div>
                        <small class="field__help">
                            É recomendada uma imagem em formato PNG ou SVG, com fundo transparente, com uma proporção horizontal e para ser usada sobre fundos escuros ou da cor abaixo. Se não existir, será usado o logótipo invertido.
                        </small>
                    </div>

                    <div class="field">
                        <label class="label">Cor</label>
                        <setting-color-picker class="mt-2" name="site-color" value="{{ Setting::get('site-color') ?? '#0099ff' }}" {{ Setting::has('site-color') ? 'is-setting' : '' }} />
                    </div>

                    <div class="field">
                        <label class="label">
                            Imagem do cabeçalho
                            <span class="label__optional">(opcional)</span>
                        </label>
                        <div class="control">
                            <setting-file-picker name="site-hero" path="imagens" accept="image/*" title="Escolher imagens do cabeçalho…" value="{{ Setting::get('site-hero') }}" multiple></setting-file-picker>
                        </div>
                    </div>

                </div>

                <h6 class="font-headline mb-2 mt-3 text-gray-600">Tipografia</h6>
                <div class="admin-settings__section__content admin-settings__section__body">
                    <typography-options name="setting[site-typography]" value="{{ Setting::get('site-typography') }}" />
                </div>
            </div>
        </section>

        <div class="admin-settings__section">
            <header class="admin-settings__section__header">
                <h3 class="admin-settings__section__title">Menu</h3>
            </header>
            <div class="admin-settings__section__content">
                <div class="admin-settings__section__body">
                    <menu-editor name="setting[menu]" value="{{ Setting::get('menu', '[]') }}"></menu-editor>
                </div>
            </div>
        </div>

        <div class="admin-settings__section">
            <header class="admin-settings__section__header">
                <h3 class="admin-settings__section__title">Destaque na página inicial</h3>
                <p class="admin-settings__section__desc">
                    Este destaque aparecerá na página inicial, no lugar da fotografia de topo.
                </p>
            </header>
            <div class="admin-settings__section__content">
                <div class="admin-settings__section__body">
                    <x-forms.input name="setting[highlight-title]" label="Título" :value="Setting::get('highlight-title')" />
                    <x-forms.input name="setting[highlight-text]" label="Texto" :value="Setting::get('highlight-text')" />
                    <x-forms.input name="setting[highlight-link]" label="Ligação" :value="Setting::get('highlight-link')" type="url" />

                    @foreach(['highlight-logo' => ['logótipo', 'logos'], 'highlight-bg' => ['imagem de fundo', 'imagens']] as $name => [$label, $path])
                        <div class="field">
                            <label class="label">
                                {{ ucfirst($label) }}
                                <span class="label__optional">(opcional)</span>
                            </label>
                            <div class="control">
                                <setting-file-picker name="{{ $name }}" path="{{ $path }}" accept="image/*" title="Escolher {{ $label }}…" value="{{ Setting::get($name) }}"></setting-file-picker>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>

        <div class="admin-settings__actions">
            <button type="submit" class="button button--primary">Guardar</button>
        </div>
    </form>
@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('admin-content')
    <div class="grid grid-cols-3 gap-4">
        @foreach($cards as $card)
            <div class="rounded bg-white shadow">
                <div class="flex gap-x-4 p-4 items-center">
                    <div class="text-gray-400 text-xl text-center px-2">
                        <span class="fa-fw far {{ $card['icon'] }}"></span>
                    </div>
                    <div>
                        <p class="text-sm font-medium text-gray-500">{{ $card['label'] }}</p>
                        <p class="text-xl font-bold">{{ $card['value'] }}</p>
                    </div>
                </div>
                <div class="bg-gray-100 px-4 py-2">
                    <a class="text-sm font-medium text-primary-500 hover:text-primary-600" href="{{ $card['url'] }}">{{ $card['link_label'] ?? 'Ver mais…' }}</a>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/domains.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header">
        <h1 class="admin-layout__header__title">
            Domínios
        </h1>
    </header>

    <livewire:domains />
@endsection

@push('styles')
    @livewireStyles
@endpush

@push('scripts')
    @livewireScripts
@endpush

resources/views/admin/events.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header md:gap-3">
        <h1 class="admin-layout__header__title">
            Eventos
        </h1>
    </header>

    <events-list :value='{!! $events->toJson() !!}' controller-url="{{ route('api.eventos.store') }}">
        <div class="text-center text-grey-300">
            Loading…
        </div>
    </events-list>
@endsection

resources/views/admin/extensions.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header md:gap-3">
        <h1 class="admin-layout__header__title">
            Extensões
        </h1>
    </header>

    @unless($addons->isEmpty())
        <div class="sautor-list">
            @foreach($addons as $addon)
                <div class="sautor-list__item">
                    <div class="sautor-list__item__status {{ $addon->isEnabled() ? 'sautor-list__item__status--success sautor-list__item__status--glow' : 'sautor-list__item__status--danger' }}"></div>
                    <div class="sautor-list__item__logo">
                     <span class="sautor-list__item__logo__icon sautor-list__item__logo__icon--strong">
                          <span class="fad fa-{{ $addon->icon }}"></span>
                     </span>
                    </div>
                    <div class="sautor-list__item__data">
                        <p class="sautor-list__item__name">
                            <span class="font-weight-bold">{{ $addon->label }}</span>
                            @if($addon->isGroupAddon())
                                <span class="badge badge--info ml-2"><span class="fas fa-users"></span> Extensão de grupo</span>
                            @elseif($addon->isTogglablePerGroup())
                                <span class="badge badge--success ml-2"><span class="fas fa-toggle-on"></span> Ativável por grupo</span>
                            @endif
                        </p>
                        @unless(empty($addon->description))
                            <p class="sautor-list__item__meta">{{ $addon->description }}</p>
                        @endunless
                    </div>
                    @if($addon->isEnabled())
                        <form action="{{ route('admin.extensoes.disable', $addon->key) }}" method="POST" class="sautor-list__item__actions">
                            @method('DELETE')
                            @csrf
                            <button type="submit">
                                <span class="far fa-times"></span>
                            </button>
                        </form>
                    @else
                        <form action="{{ route('admin.extensoes.enable', $addon->key) }}" method="POST" class="sautor-list__item__actions">
                            @csrf
                            <button type="submit">
                                <span class="far fa-check"></span>
                            </button>
                        </form>
                    @endif
                </div>
            @endforeach
        </div>
    @else
        <p class="sautor-list--empty">
            Não existem extensões instaladas
        </p>
    @endunless
@endsection

resources/views/admin/groups.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header md:gap-3">
        <h1 class="admin-layout__header__title">
            Grupos
        </h1>
        @can('create', \Sautor\Core\Models\Grupo::class)
            <div class="admin-layout__header__actions">
                <button type="button" class="button button--responsive" @click.prevent="openModal('addGroup')">
                    <span class="far fa-plus mr-2"></span>
                    Adicionar
                </button>
            </div>
        @endcan
    </header>

    <x-groups.list full :grupos="$grupos" :badge="function($g) {
                                    $output = '';
                                    if($g->visibilidade === 'nao_listado') { $output .= ' <span class=\'badge\'>Não listado</span>'; }
                                    if($g->visibilidade === 'oculto') { $output .= ' <span class=\'badge\'>Oculto</span>'; }
    return $output !== '' ? $output : null;
    }" />

    @if($gruposEliminados->isNotEmpty())
        <h2 class="title title--sm mt-6 mb-4">Grupos eliminados</h2>
        <x-groups.list full :grupos="$gruposEliminados" :actions="function($g) {
                        return [
                            ['icon' => 'far fa-fw fa-undo', 'label' => 'Restaurar', 'modal' => 'restoreModal'.$g->id]
                        ];
                    }" />

        @foreach($gruposEliminados as $grp)
            <x-groups.restore-modal :group="$grp" />
        @endforeach
    @endif

    <x-groups.add-modal :slugs="$slugs" />
@endsection

resources/views/admin/people.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header md:gap-3">
        <h1 class="admin-layout__header__title">
            Pessoas
        </h1>
        @can('store', \Sautor\Core\Models\Pessoa::class)
            <div class="admin-layout__header__actions">
                <a href="{{ route('pessoas.create') }}" class="button button--responsive">
                    <span class="far fa-user-plus mr-2"></span>
                    Registar
                </a>
            </div>
        @endcan
    </header>

    <x-people.list full :pessoas="$people" :meta="function($p) { return $p->grupos->pluck('nome')->implode(', '); }" />

    @if(method_exists($people, 'links'))
        <div class="mt-4">
            {{ $people->links() }}
        </div>
    @endif
@endsection

resources/views/admin/permissions.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header md:gap-3">
        <h1 class="admin-layout__header__title">
            Permissões
        </h1>
    </header>

    <div class="alert alert--info -mt-6 mb-6" role="alert">
        Para atribuir funções e permissões a uma pessoa, aceda à sua ficha pessoal.
    </div>

    <h3 class="title title--sm mb-4">Funções</h3>

    <div class="grid grid-cols-1 2xl:grid-cols-2 gap-3">
        @foreach($roles as $role)
            <div class="bg-white rounded-lg shadow px-8 md:px-6 py-4 -mx-8 md:mx-0">
                <h4 class="title title--xs mb-3">{{ ucfirst($role->name) }}</h4>
                <div class="grid md:grid-cols-3 gap-4">
                    <div>
                        <h5 class="font-accent text-sm text-gray-700 mb-2">Permissões</h5>
                        <ul class="admin-text-list">
                            @foreach($role->permissions as $permission)
                                <li>{{ ucfirst($permission->name) }}</li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="col-span-2">
                        <h5 class="font-accent text-sm text-gray-700 mb-2">Pessoas</h5>

                        <x-people.list full :pessoas="\Sautor\Core\Models\Pessoa::role($role)->get()" />
                    </div>
                </div>
            </div>
        @endforeach
    </div>

    <h3 class="title title--sm mt-6 mb-4">Permissões</h3>

    <div class="grid grid-cols-1 md:grid-cols-2 2xl:grid-cols-3 gap-3">
        @foreach($permissions as $permission)
            <div class="bg-white rounded-lg shadow px-8 md:px-6 py-4 -mx-8 md:mx-0">
                <h4 class="title title--xs mb-3">{{ ucfirst($permission->name) }}</h4>

                <h5 class="font-accent text-sm text-gray-700 mb-2">Pessoas</h5>

                <x-people.list full :pessoas="\Sautor\Core\Models\Pessoa::permission($permission)->get()" />
            </div>
        @endforeach
    </div>
@endsection

resources/views/admin/redirects.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header">
        <h1 class="admin-layout__header__title">
            Redirecionamentos
        </h1>
    </header>

    <livewire:redirects />
@endsection

@push('styles')
    @livewireStyles
@endpush

@push('scripts')
    @livewireScripts
@endpush

resources/views/admin/settings.blade.php
@extends('layouts.admin')

@section('admin-content')
    <header class="admin-layout__header md:gap-3">
        <h1 class="admin-layout__header__title">
            Definições
        </h1>
    </header>

    <form method="POST" enctype="multipart/form-data">
    @csrf

        <div class="admin-settings__section">
            <header class="admin-settings__section__header">
                <h3 class="admin-settings__section__title">Modo de manutenção</h3>
            </header>
            <div class="admin-settings__section__content">
                <div class="admin-settings__section__body">
                    <x-forms.checkbox name="setting[man]" label="Ativo" :value="Setting::get('man')" />
                    <x-forms.input name="setting[man-title]" label="Título" :value="Setting::get('man-title')" />
                    <x-forms.input name="setting[man-subtitle]" label="Subtítulo" :value="Setting::get('man-subtitle')" />
                    <div class="field">
                        <label class="label">Conteúdo</label>
                        <div class="control">
                            <small-content-editor name="setting[man-content]" value="{{ Setting::get('man-content') }}"></small-content-editor>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="admin-settings__section">
            <header class="admin-settings__section__header">
                <h3 class="admin-settings__section__title">Proteção de dados e Privacidade</h3>
            </header>
            <div class="admin-settings__section__content">
                <div class="admin-settings__section__body">
                    <x-forms.checkbox name="setting[gdpr-blockData]" label="Bloquear o acesso a pessoas sem consentimento ativo" :value="Setting::get('gdpr-blockData')" />
                    <x-forms.checkbox name="setting[gdpr-requireForLogin]" label="Obrigar os utilizadores a consentir para poder entrar" :value="Setting::get('gdpr-requireForLogin')" />
                    <div class="field">
                        <label class="label">Informação</label>
                        <div class="control">
                            <small-content-editor name="setting[gdpr-info]" value="{{ Setting::get('gdpr-info') }}"></small-content-editor>
                        </div>
                    </div>
                    <x-forms.textarea name="setting[gdpr-authorization]" label="Autorização" :value="Setting::get('gdpr-authorization')" />
                    <x-forms.textarea name="setting[gdpr-authorization-adult]" label="Autorização para documento - adultos" :value="Setting::get('gdpr-authorization-adult')" />
                    <x-forms.textarea name="setting[gdpr-authorization-minor]" label="Autorização para documento - menores" :value="Setting::get('gdpr-authorization-minor')" />

                    <x-forms.input name="setting[privacy-policy-link]" label="Ligação para a Política de Privacidade" :value="Setting::get('privacy-policy-link')" type="url" />
                </div>
            </div>
        </div>

        <div class="admin-settings__section">
            <header class="admin-settings__section__header">
                <h3 class="admin-settings__section__title">Banner de Cookies</h3>
            </header>
            <div class="admin-settings__section__content">
                <div class="admin-settings__section__body">
                    <x-forms.checkbox name="setting[cookie-banner]" label="Mostrar banner de cookies" :value="Setting::get('cookie-banner')" />
                    <x-forms.input name="setting[cookie-duration]" label="Duração do cookie" :value="Setting::get('cookie-duration')" after="dias" type="number" :options="['placeholder' => 30, 'min' => 1, 'step' => 1]" />
                    <x-forms.input name="setting[cookie-title]" label="Título" :value="Setting::get('cookie-title')" />
                    <div class="field">
                        <label class="label">Conteúdo</label>
                        <div class="control">
                            <small-content-editor name="setting[cookie-content]" value="{{ Setting::get('cookie-content') }}"></small-content-editor>
                        </div>
                    </div>
                    <x-forms.input name="setting[cookie-more-link]" label="Ligação da Política de Cookies" :value="Setting::get('cookie-more-link')" type="url" />
                </div>
            </div>
        </div>

        <div class="admin-settings__section">
            <header class="admin-settings__section__header">
                <h3 class="admin-settings__section__title">Contactos</h3>
            </header>
            <div class="admin-settings__section__content">
                <div class="admin-settings__section__body">
                    <x-forms.textarea name="setting[contact-address]" label="Morada" :value="Setting::get('contact-address')" />
                    <x-forms.input name="setting[contact-email]" label="Endereço de email" :value="Setting::get('contact-email')" type="email" before="<span class='far fa-at fa-fw'></span>" />
                    <x-forms.input name="setting[social-facebook]" label="Facebook" :value="Setting::get('social-facebook')" type="url" before="<span class='fab fa-facebook fa-fw'></span>" />
                    <x-forms.input name="setting[social-instagram]" label="Instagram" :value="Setting::get('social-instagram')" type="url" before="<span class='fab fa-instagram fa-fw'></span>" />
                    <x-forms.input name="setting[social-twitter]" label="Twitter" :value="Setting::get('social-twitter')" type="url" before="<span class='fab fa-twitter fa-fw'></span>" />
                    <x-forms.input name="setting[social-youtube]" label="YouTube" :value="Setting::get('social-youtube')" type="url" before="<span class='fab fa-youtube fa-fw'></span>" />
                    <x-forms.input name="setting[social-spotify]" label="Spotify" :value="Setting::get('social-spotify')" type="url" before="<span class='fab fa-spotify fa-fw'></span>" />
                </div>
            </div>
        </div>

        <div class="admin-settings__actions">
            <button type="submit" class="button button--primary">Guardar</button>
        </div>
    </form>
@endsection