routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('www.'.config('app.domain'))->group(function () {
    Route::get('{slug?}', function ($slug = null) {
        return redirect(config('app.url').($slug ?? ''), 301);
    })->where('slug', '(.*)');
});

// Authentication Routes
Route::get('entrar', 'Auth\LoginController@showLoginForm')->middleware('guest')->name('login');
Route::post('entrar', 'Auth\LoginController@login')->middleware('guest');
Route::post('sair', 'Auth\LoginController@logout')->name('logout');

// Grupos
Route::prefix('grupos/{grupo}')->name('grupo.')->group(__DIR__.'/group.php');

Route::domain(config('app.domain'))->group(function () {
    // Social Auth routes
    Route::namespace('Auth')->prefix('auth/{provider}')->name('social.')->group(function () {
        Route::get('/', 'LoginController@socialRedirect')->name('redirect');
        Route::get('callback', 'LoginController@socialCallback')->name('callback');

        // Social Link routes
        Route::get('link', 'SocialController@link')->name('link')->middleware('auth');
        Route::post('link', 'SocialController@linkConfirm')->name('linkConfirm')->middleware('auth');
        Route::delete('link', 'SocialController@unlink')->name('unlink')->middleware('auth');
    });

    // Password Reset Routes...
    Route::namespace('Auth')->prefix('password')->name('password.')->middleware('guest')->group(function () {
        Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('request');
        Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');
        Route::get('reset/{token}', 'ResetPasswordController@showResetForm')->name('reset');
        Route::post('reset', 'ResetPasswordController@reset');
    });

    Route::middleware('maintenance')->group(function () {
        Route::get('/', 'HomeController@index')->name('home');

        // Noticias
        Route::prefix('noticias')->name('noticias.')->group(function () {
            Route::get('/', 'NoticiasController@index')->name('index');
            Route::get('{noticia}', 'NoticiasController@show')->name('show');
        });

        // Pessoas
        Route::resource('pessoas', 'PessoasController', ['except' => ['index']]);
        Route::resource('pessoas.passos', 'PassosController', ['only' => ['store', 'destroy']]);
        Route::resource('pessoas.consentimentos', 'ConsentimentosController', ['only' => ['store', 'show', 'destroy']]);
        Route::prefix('pessoas')->name('pessoas.')->middleware('auth')->group(function () {
            Route::patch('{pessoa}/foto', 'PessoasController@updatePhoto')->name('updateFoto');
            Route::get('{pessoa}/enviar-link', 'PessoasController@sendPasswordResetLink')->name('sendResetLink');
            Route::post('{pessoa}/relacoes', 'RelacoesController@store')->name('relacoes.store');
            Route::delete('{pessoa}/relacoes/{pessoa2}', 'RelacoesController@destroy')->name('relacoes.destroy');

            Route::post('{pessoa}/permissoes', 'PermissionsController@addPermission')->name('permissions.add');
            Route::delete('{pessoa}/permissoes/{permission}', 'PermissionsController@removePermission')->name('permissions.remove');
            Route::post('{pessoa}/papeis', 'PermissionsController@addRole')->name('permissions.addRole');
            Route::delete('{pessoa}/papeis/{role}', 'PermissionsController@removeRole')->name('permissions.removeRole');
        });

        // Eu
        Route::middleware(['auth'])->prefix('eu')->name('me.')->group(function () {
            Route::get('/', 'EuController@conta')->name('account');
            Route::get('perfil', 'EuController@perfil')->name('profile');
            Route::get('edit', 'EuController@editPerfil')->name('editProfile');
            Route::get('grupos', 'EuController@grupos')->name('groups');
            Route::post('password', 'EuController@changePassword')->name('changePassword');
            Route::get('consentimento', 'ConsentimentosController@showRequest')->name('showConsentRequest');
            Route::post('consentimento', 'ConsentimentosController@storeRequest')->name('storeConsentRequest');
        });

        // Admin
        Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
            Route::get('/', 'AdminController@index')->name('dashboard')->middleware(['permission:ver pessoas|gerir pessoas|gerir grupos|gerir permissões|gerir notícias|gerir páginas|gerir opções|gerir eventos']);
            Route::get('pessoas', 'AdminController@pessoas')->name('people')->middleware(['permission:ver pessoas|gerir pessoas']);
            Route::resource('noticias', 'Admin\\NoticiasController', ['except' => ['show', 'store', 'update']])->middleware(['permission:gerir notícias']);
            Route::resource('paginas', 'Admin\\PaginasController', ['except' => ['show', 'store', 'update']])->middleware(['permission:gerir páginas']);
            Route::get('eventos', 'Admin\\EventosController@index')->name('eventos')->middleware(['permission:gerir eventos']);
            Route::get('permissoes', 'AdminController@permissoes')->name('permissoes')->middleware(['permission:gerir permissões']);

            Route::middleware(['permission:gerir grupos'])->prefix('grupos')->group(function () {
                Route::get('/', 'Admin\\GruposController@index')->name('groups');
                Route::post('/', 'Admin\\GruposController@store')->name('groups.store');
                Route::put('restore', 'Admin\\GruposController@restore')->name('groups.restore');
            });

            Route::middleware(['permission:gerir opções'])->group(function () {
                Route::get('extensoes', 'Admin\\AddonController@index')->name('extensoes');
                Route::post('extensoes/{key}', 'Admin\\AddonController@enable')->name('extensoes.enable');
                Route::delete('extensoes/{key}', 'Admin\\AddonController@disable')->name('extensoes.disable');

                Route::get('personalizar', 'Admin\\OpcoesController@personalizar')->name('personalizar');
                Route::post('personalizar', 'Admin\\OpcoesController@updatePersonalizar')->name('personalizar.update');

                Route::get('redirects', 'AdminController@redirects')->name('redirects');

                Route::get('definicoes', 'Admin\\OpcoesController@definicoes')->name('definicoes');
                Route::post('definicoes', 'Admin\\OpcoesController@updateDefinicoes')->name('definicoes.update');
            });

            Route::middleware(['permission:gerir domínios'])->get('dominios', 'AdminController@domains')->name('domains');
        });

        // 2FA
        Route::view('2fa-required', 'two-factor::notice')->name('2fa.notice');

        // Media
        Route::get('media/{uuid}', 'MediaController@show')->name('media');



        // Page catch all
        Route::get('{slug}', 'PaginasController@show')
            ->where('slug', '(.*)')->name('paginas.show');
    });
});

Route::domain('{grupo}.'.config('app.domain'))->group(function () {
    Route::get('{slug?}', function (Sautor\Core\Models\Grupo $grupo, $slug = null) {
        return redirect(config('app.url').route('grupo.index', $grupo, false).($slug ? '/'.$slug : ''));
    })->where('slug', '(.*)');
});

Route::domain('{grupo:dominio}')->where(['grupo' => '[a-z0-9.]+'])->name('grupo-dominio.')->middleware('maintenance')->group(function () {
    Route::get('noticias/{noticia}', 'GruposController@noticia')->where(['noticia' => '[0-9]+'])->name('noticia');

    require __DIR__.'/group.php';
});

resources/views/people/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="people-create__container">
        <h1 class="title mb-12">Registar pessoa</h1>

        @php($scope = 'new-pessoa')
        <form action="{{ route('pessoas.store') }}" method="POST" data-vv-scope="{{ $scope }}"
              @submit.prevent="validateForm">
            @csrf

            @unless(empty($relacao))
                <input type="hidden" name="relacao" value="{{ $relacao }}">
                <input type="hidden" name="relate_with" value="{{ $related_person->id }}">
                <div class="alert alert--info mb-6">
                    Esta pessoa será registada com <strong>{{ $related_person->nome }}</strong> como
                    <strong>{{ Sautor\Core\Models\Relacao::DESC_NAMES[$relacao][$related_person->genero] }}</strong>.
                </div>
            @endunless

            @unless(empty($grupo) and empty($anoletivo) and empty($cargo) and empty($responsavel))
                <input type="hidden" name="anoletivo" value="{{ $anoletivo }}">
                <input type="hidden" name="cargo" value="{{ $cargo }}">
                <input type="hidden" name="responsavel" value="{{ $responsavel }}">
                <input type="hidden" name="register_in" value="{{ $grupo->id }}">
                <div class="alert alert--info mb-6">
                    Esta pessoa será inscrita
                    @if($anoletivo == 1)
                        durante este ano letivo
                    @endif
                    @unless(empty($cargo))
                        com o cargo <strong>{{ $cargo }}</strong>
                    @endunless
                    @if($responsavel == 1)
                        como responsável de
                    @else
                        em
                    @endif
                    <strong>{{ $grupo->nome }}</strong>.
                </div>
            @endunless

            @include('people.form')

            <div class="people-create__actions">
                <button type="submit" class="button button--primary">Registar</button>
            </div>
        </form>
    </div>
@endsection

resources/views/people/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="people-edit__container">
        <h1 class="title mb-12">Editar pessoa</h1>

        @php($scope = 'edit-pessoa')
        <form action="{{ route('pessoas.update', $pessoa) }}" method="POST" data-vv-scope="{{ $scope }}" @submit.prevent="validateForm">
            @csrf
            @method('PUT')

            @include('people.form')

            <div class="people-edit__actions">
                <button type="submit" class="button button--primary">Editar</button>
            </div>
        </form>
    </div>
@endsection

resources/views/people/form.blade.php
<div class="people-form__section">
    <header class="people-form__section__header">
        <h3 class="people-form__section__title">
            Informação pessoal
        </h3>
    </header>
    <div class="group-settings__section__content">
        <div class="group-settings__section__body">

            <x-forms.input name="nome" label="Nome completo" required rules="required" :value="isset($pessoa) ? $pessoa->nome : null" :scope="$scope" />
            <x-forms.input name="data_nascimento" label="Data de nascimento" :value="isset($pessoa->data_nascimento) ? $pessoa->data_nascimento->format('Y-m-d') : null" rules="date_format:yyyy-MM-dd" type="date" :options="['placeholder' => 'AAAA-MM-DD']" :scope="$scope" />
            <x-forms.radio name="genero" label="Género" required rules="required" :value="isset($pessoa) ? $pessoa->genero : null" :list="['M' => 'Masculino', 'F' => 'Feminino']" />
            <x-forms.input name="profissao" label="Profissão" :value="isset($pessoa) ? $pessoa->profissao : null" :scope="$scope" />
            <x-forms.input name="nic" label="Número de Identificação Civil" required :rules="'required|unique_pes:nic'.(isset($pessoa)?','.$pessoa->id:'')" help="N.º de Cartão de Cidadão" :value="isset($pessoa) ? $pessoa->nic : null" :scope="$scope" />
            <x-forms.input name="nus" label="Número de Utente de Saúde" :value="isset($pessoa) ? $pessoa->nus : null" :scope="$scope" />
            <x-forms.input name="nif" label="Número de Identificação Fiscal" :value="isset($pessoa) ? $pessoa->nif : null" :scope="$scope" />


        </div>
    </div>
</div>

@if(Auth::user()->can('gerir pessoas'))

<div class="people-form__section">
    <header class="people-form__section__header">
        <h3 class="people-form__section__title">
            Informação eclesial
        </h3>
    </header>
    <div class="group-settings__section__content">
        <div class="group-settings__section__body">

            <x-forms.radio name="ordem" label="Ordem" required :list="[null => 'Nenhuma', 'diacono' => 'Diaconado', 'sacerdote' => 'Sacerdócio']" :value="isset($pessoa) ? $pessoa->ordem : null" :scope="$scope" />

        </div>
    </div>
</div>

@endif

<div class="people-form__section">
    <header class="people-form__section__header">
        <h3 class="people-form__section__title">
            Informação de contacto
        </h3>
    </header>
    <div class="group-settings__section__content">
        <div class="group-settings__section__body">

            <x-forms.textarea name="morada" label="Morada" :value="isset($pessoa) ? $pessoa->morada : null" :scope="$scope" :options="['rows' => 2]" />
            <x-forms.input name="email" label="Endereço de e-mail" type="email" :value="isset($pessoa) ? $pessoa->email : null" :scope="$scope" :rules="'email|unique_pes:email'.(isset($pessoa)?','.$pessoa->id:'')" />
            <x-forms.input name="telefone" label="Número de telefone" type="tel" :value="isset($pessoa) ? $pessoa->telefone : null" :scope="$scope" />


        </div>
    </div>
</div>