routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::domain('www.'.config('app.domain'))->group(function () {
    Route::get('{slug?}', function ($slug = null) {
        return redirect(config('app.url').($slug ?? ''), 301);
    })->where('slug', '(.*)');
});

// Authentication Routes
Route::get('entrar', 'Auth\LoginController@showLoginForm')->middleware('guest')->name('login');
Route::post('entrar', 'Auth\LoginController@login')->middleware('guest');
Route::post('sair', 'Auth\LoginController@logout')->name('logout');

// Grupos
Route::prefix('grupos/{grupo}')->name('grupo.')->group(__DIR__.'/group.php');

Route::domain(config('app.domain'))->group(function () {
    // Social Auth routes
    Route::namespace('Auth')->prefix('auth/{provider}')->name('social.')->group(function () {
        Route::get('/', 'LoginController@socialRedirect')->name('redirect');
        Route::get('callback', 'LoginController@socialCallback')->name('callback');

        // Social Link routes
        Route::get('link', 'SocialController@link')->name('link')->middleware('auth');
        Route::post('link', 'SocialController@linkConfirm')->name('linkConfirm')->middleware('auth');
        Route::delete('link', 'SocialController@unlink')->name('unlink')->middleware('auth');
    });

    // Password Reset Routes...
    Route::namespace('Auth')->prefix('password')->name('password.')->middleware('guest')->group(function () {
        Route::get('reset', 'ForgotPasswordController@showLinkRequestForm')->name('request');
        Route::post('email', 'ForgotPasswordController@sendResetLinkEmail')->name('email');
        Route::get('reset/{token}', 'ResetPasswordController@showResetForm')->name('reset');
        Route::post('reset', 'ResetPasswordController@reset');
    });

    Route::middleware('maintenance')->group(function () {
        Route::get('/', 'HomeController@index')->name('home');

        // Noticias
        Route::prefix('noticias')->name('noticias.')->group(function () {
            Route::get('/', 'NoticiasController@index')->name('index');
            Route::get('{noticia}', 'NoticiasController@show')->name('show');
        });

        // Pessoas
        Route::resource('pessoas', 'PessoasController', ['except' => ['index']]);
        Route::resource('pessoas.passos', 'PassosController', ['only' => ['store', 'destroy']]);
        Route::resource('pessoas.consentimentos', 'ConsentimentosController', ['only' => ['store', 'show', 'destroy']]);
        Route::prefix('pessoas')->name('pessoas.')->middleware('auth')->group(function () {
            Route::patch('{pessoa}/foto', 'PessoasController@updatePhoto')->name('updateFoto');
            Route::get('{pessoa}/enviar-link', 'PessoasController@sendPasswordResetLink')->name('sendResetLink');
            Route::post('{pessoa}/relacoes', 'RelacoesController@store')->name('relacoes.store');
            Route::delete('{pessoa}/relacoes/{pessoa2}', 'RelacoesController@destroy')->name('relacoes.destroy');

            Route::post('{pessoa}/permissoes', 'PermissionsController@addPermission')->name('permissions.add');
            Route::delete('{pessoa}/permissoes/{permission}', 'PermissionsController@removePermission')->name('permissions.remove');
            Route::post('{pessoa}/papeis', 'PermissionsController@addRole')->name('permissions.addRole');
            Route::delete('{pessoa}/papeis/{role}', 'PermissionsController@removeRole')->name('permissions.removeRole');
        });

        // Eu
        Route::middleware(['auth'])->prefix('eu')->name('me.')->group(function () {
            Route::get('/', 'EuController@conta')->name('account');
            Route::get('perfil', 'EuController@perfil')->name('profile');
            Route::get('edit', 'EuController@editPerfil')->name('editProfile');
            Route::get('grupos', 'EuController@grupos')->name('groups');
            Route::post('password', 'EuController@changePassword')->name('changePassword');
            Route::get('consentimento', 'ConsentimentosController@showRequest')->name('showConsentRequest');
            Route::post('consentimento', 'ConsentimentosController@storeRequest')->name('storeConsentRequest');
        });

        // Admin
        Route::middleware(['auth'])->prefix('admin')->name('admin.')->group(function () {
            Route::get('/', 'AdminController@index')->name('dashboard')->middleware(['permission:ver pessoas|gerir pessoas|gerir grupos|gerir permissões|gerir notícias|gerir páginas|gerir opções|gerir eventos']);
            Route::get('pessoas', 'AdminController@pessoas')->name('people')->middleware(['permission:ver pessoas|gerir pessoas']);
            Route::resource('noticias', 'Admin\\NoticiasController', ['except' => ['show', 'store', 'update']])->middleware(['permission:gerir notícias']);
            Route::resource('paginas', 'Admin\\PaginasController', ['except' => ['show', 'store', 'update']])->middleware(['permission:gerir páginas']);
            Route::get('eventos', 'Admin\\EventosController@index')->name('eventos')->middleware(['permission:gerir eventos']);
            Route::get('permissoes', 'AdminController@permissoes')->name('permissoes')->middleware(['permission:gerir permissões']);

            Route::middleware(['permission:gerir grupos'])->prefix('grupos')->group(function () {
                Route::get('/', 'Admin\\GruposController@index')->name('groups');
                Route::post('/', 'Admin\\GruposController@store')->name('groups.store');
                Route::put('restore', 'Admin\\GruposController@restore')->name('groups.restore');
            });

            Route::middleware(['permission:gerir opções'])->group(function () {
                Route::get('extensoes', 'Admin\\AddonController@index')->name('extensoes');
                Route::post('extensoes/{key}', 'Admin\\AddonController@enable')->name('extensoes.enable');
                Route::delete('extensoes/{key}', 'Admin\\AddonController@disable')->name('extensoes.disable');

                Route::get('personalizar', 'Admin\\OpcoesController@personalizar')->name('personalizar');
                Route::post('personalizar', 'Admin\\OpcoesController@updatePersonalizar')->name('personalizar.update');

                Route::get('redirects', 'AdminController@redirects')->name('redirects');

                Route::get('definicoes', 'Admin\\OpcoesController@definicoes')->name('definicoes');
                Route::post('definicoes', 'Admin\\OpcoesController@updateDefinicoes')->name('definicoes.update');
            });

            Route::middleware(['permission:gerir domínios'])->get('dominios', 'AdminController@domains')->name('domains');
        });

        // 2FA
        Route::view('2fa-required', 'two-factor::notice')->name('2fa.notice');

        // Media
        Route::get('media/{uuid}', 'MediaController@show')->name('media');



        // Page catch all
        Route::get('{slug}', 'PaginasController@show')
            ->where('slug', '(.*)')->name('paginas.show');
    });
});

Route::domain('{grupo}.'.config('app.domain'))->group(function () {
    Route::get('{slug?}', function (Sautor\Core\Models\Grupo $grupo, $slug = null) {
        return redirect(config('app.url').route('grupo.index', $grupo, false).($slug ? '/'.$slug : ''));
    })->where('slug', '(.*)');
});

Route::domain('{grupo:dominio}')->where(['grupo' => '[a-z0-9.]+'])->name('grupo-dominio.')->middleware('maintenance')->group(function () {
    Route::get('noticias/{noticia}', 'GruposController@noticia')->where(['noticia' => '[0-9]+'])->name('noticia');

    require __DIR__.'/group.php';
});

resources/views/layouts/admin.blade.php
@extends('layouts.app')

@section('content')
    <div class="admin-layout__container">
        <aside class="side-nav">
            <h6 class="side-nav__title">Administração</h6>
            @canany(['ver pessoas', 'gerir pessoas'])
                <a href="{{ route('admin.people') }}"
                   class="side-nav__item @if(Route::currentRouteName() === 'admin.people') side-nav__item--active @endif ">
                    <span class="side-nav__item__icon far fa-fw fa-user-friends"></span>
                    <span class="side-nav__item__label">
                        Pessoas
                    </span>
                </a>
            @endcanany
            @can('gerir grupos')
                <a href="{{ route('admin.groups') }}"
                   class="side-nav__item @if(Route::currentRouteName() === 'admin.groups') side-nav__item--active @endif ">
                    <span class="side-nav__item__icon far fa-fw fa-users"></span>
                    <span class="side-nav__item__label">
                        Grupos
                    </span>
                </a>
            @endcan
            @can('gerir notícias')
                <a href="{{ route('admin.noticias.index') }}"
                   class="side-nav__item @if(Route::currentRouteName() === 'admin.noticias.index') side-nav__item--active @endif ">
                    <span class="side-nav__item__icon far fa-fw fa-newspaper"></span>
                    <span class="side-nav__item__label">
                        Notícias
                    </span>
                </a>
            @endcan
            @can('gerir páginas')
                <a href="{{ route('admin.paginas.index') }}"
                   class="side-nav__item @if(Route::currentRouteName() === 'admin.paginas.index') side-nav__item--active @endif ">
                    <span class="side-nav__item__icon far fa-fw fa-file-alt"></span>
                    <span class="side-nav__item__label">
                        Páginas
                    </span>
                </a>
            @endcan
            @can('gerir eventos')
                <a href="{{ route('admin.eventos') }}"
                   class="side-nav__item @if(Route::currentRouteName() === 'admin.eventos') side-nav__item--active @endif ">
                    <span class="side-nav__item__icon far fa-fw fa-calendar-alt"></span>
                    <span class="side-nav__item__label">
                        Eventos
                    </span>
                </a>
            @endcan
            @can('gerir permissões')
                <a href="{{ route('admin.permissoes') }}"
                   class="side-nav__item @if(Route::currentRouteName() === 'admin.permissoes') side-nav__item--active @endif ">
                    <span class="side-nav__item__icon far fa-fw fa-shield-alt"></span>
                    <span class="side-nav__item__label">
                        Permissões
                    </span>
                </a>
            @endcan
            @can('gerir opções')
                @if(\AddonService::all()->isNotEmpty())
                    <a href="{{ route('admin.extensoes') }}"
                       class="side-nav__item @if(Route::currentRouteName() === 'admin.extensoes') side-nav__item--active @endif ">
                        <span class="side-nav__item__icon far fa-fw fa-puzzle-piece"></span>
                        <span class="side-nav__item__label">
                            Extensões
                        </span>
                    </a>
                @endif
                <a href="{{ route('admin.personalizar') }}"
                   class="side-nav__item @if(Route::currentRouteName() === 'admin.personalizar') side-nav__item--active @endif ">
                    <span class="side-nav__item__icon far fa-fw fa-pencil-paintbrush"></span>
                    <span class="side-nav__item__label">
                        Personalizar
                    </span>
                </a>
                    <a href="{{ route('admin.redirects') }}"
                       class="side-nav__item @if(Route::currentRouteName() === 'admin.redirects') side-nav__item--active @endif ">
                        <span class="side-nav__item__icon far fa-fw fa-directions"></span>
                        <span class="side-nav__item__label">
                        Redirecionamentos
                    </span>
                    </a>
                <a href="{{ route('admin.definicoes') }}"
                   class="side-nav__item @if(Route::currentRouteName() === 'admin.definicoes') side-nav__item--active @endif ">
                    <span class="side-nav__item__icon far fa-fw fa-cogs"></span>
                    <span class="side-nav__item__label">
                        Definições
                    </span>
                </a>
            @endcan
            @can('gerir domínios')
                <a href="{{ route('admin.domains') }}"
                   class="side-nav__item">
                    <span class="side-nav__item__icon far fa-fw fa-server"></span>
                    <span class="side-nav__item__label">
                        Domínios
                    </span>
                </a>
            @endcan
            @can('ver logs')
                <a href="{{ route('log-viewer.index') }}"
                   class="side-nav__item">
                    <span class="side-nav__item__icon far fa-fw fa-bug"></span>
                    <span class="side-nav__item__label">
                        Ver logs
                    </span>
                </a>
            @endcan
        </aside>

        <div class="admin-layout__content">
            @yield('admin-content')
        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
@include('layouts.partials.head')

<div id="app">

  @include('layouts.partials.header')

  <div id="app_content">
    @yield('content')
  </div>

  @include('layouts.partials.footer')
  @include('layouts.partials.cookie-banner')

</div>

@include('layouts.partials.foot')

resources/views/layouts/auth.blade.php
@include('layouts.partials.head')

<div id="app" class="auth-screen @unless(empty($grupo)) auth-screen--group @endunless ">

  <div id="app-content">

    <div class="auth-screen__logo">
        @unless(empty($grupo))
            @if($grupo->logo)
                <img src="{{ $grupo->logo }}" alt="{{ $grupo->nome }}" class="login-logo">
            @else
                {{ $grupo->nome }}
            @endif
        @else
            @if(Setting::get('site-logo-invert'))
                <img src="{{ Setting::get('site-logo-invert') }}" alt="{{ config('app.name') }}" class="login-logo">
            @elseif(Setting::get('site-logo'))
                <img src="{{ Setting::get('site-logo') }}" alt="{{ config('app.name') }}" class="login-logo">
            @else
                {{ config('app.name') }}
            @endif
        @endunless
    </div>

    <div class="auth-content">
        @unless(empty($grupo))
            <h4 class="auth-content__logo">
                @if(Setting::get('site-logo'))
                    <img src="{{ Setting::get('site-logo') }}" alt="{{ config('app.name') }}">
                @else
                    {{ config('app.name') }}
                @endif
            </h4>
        @endunless

        @yield('content')
    </div>
  </div>

</div>

@include('layouts.partials.foot')

resources/views/layouts/basic.blade.php
@include('layouts.partials.head')

<div id="app">

  @includeWhen(empty($noTopbar), 'layouts.partials.topbar')

  <div id="app_content">
    @yield('content')
  </div>

  @include('layouts.partials.footer', ['basicFooter' => empty($withFooter)])

  @include('layouts.partials.cookie-banner')
</div>

@include('layouts.partials.foot')

resources/views/layouts/group-admin.blade.php
@extends('layouts.app')

@section('content')
    <div class="group-admin-layout__container">
        <aside class="side-nav">
            <h6 class="side-nav__topic">{{ $grupo->nome_curto }}</h6>
            <h6 class="side-nav__title">Gestão do grupo</h6>

            @foreach($privateMenu as $menuItem)

                <a href="{{ @$menuItem['absolute_route'] ? route($menuItem['route'], $grupo) : $grupo->route($menuItem['route'], ...($menuItem['params'] ?? [])) }}"
                   class="side-nav__item @if(Route::currentRouteName() === $menuItem['route']) side-nav__item--active @endif ">
                    <span class="side-nav__item__icon fa-fw {{ $menuItem['icon'] }}"></span>
                    <span class="side-nav__item__label">
                        {{ $menuItem['label'] }}
                    </span>
                </a>

            @endforeach

            <a href="{{ $grupo->route('index') }}"
               class="side-nav__item">
                <span class="side-nav__item__icon fa-fw far fa-arrow-left"></span>
                <span class="side-nav__item__label">
                    Voltar
                </span>
            </a>
        </aside>

        <div class="group-admin-layout__content">
            @yield('group-content')
        </div>
    </div>
@endsection